name: Update Streamlit App

on:
  schedule:
    # Runs at 00:00 every Sunday
    - cron: '0 0 * * 0'
  push:
    branches:
      - master

jobs:
  update_app:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Pull latest code and restart Streamlit
      run: |
        git pull origin master
        # Add your command to restart Streamlit app, adjust as necessary based on your deployment
        echo "Restart Streamlit app command here"